---
title: "CFR_DR_JH"
author: "Selma Gomez Orr"
date: "12/8/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages,  eval=TRUE, include=FALSE}
library(tidyverse)
library(purrr)
library(plyr)
```

```{r clean, echo=FALSE}
data <- read.csv(file = 'CFRDR_JHrev.csv')
names(data) <- c('Country', 'Confirmed', 'Deaths', 'CASE', 'DPOP','CFR', 'DR')
CFR_JH <- data %>% select("Country", "CFR")
DR_JH <- data %>% select("Country", "DR" )
```

```{r clean, echo=FALSE}
MMR <- read.csv(file = 'MMR1.csv')
list_of_names = names(MMR)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(MMR) <- list_of_names
MMR1 <- MMR %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
MMR1 <- MMR1[, col_order]

MMRData = MMR1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
dtap <- read.csv(file = 'dtap.csv')
list_of_names = names(dtap)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(dtap) <- list_of_names
dtap1 <- dtap %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
dtap1 <- dtap1[, col_order]

dtapData = dtap1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
ROT <- read.csv(file = 'ROT.csv')
list_of_names = names(ROT)
list_of_names[1]= "country"
for (i in 2:15){
  list_of_names[i] <- 2021 - i
}
names(ROT) <- list_of_names
ROT1 <- ROT %>% slice(-1)

col_order <- c("country", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
ROT1 <- ROT1[, col_order]

ROTData = ROT1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
POL <- read.csv(file = 'POL.csv')
list_of_names = names(POL)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(POL) <- list_of_names
POL1 <- POL %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
POL1 <- POL1[, col_order]

POLData = POL1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
BCG <- read.csv(file = 'BCG.csv')
list_of_names = names(BCG)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(BCG) <- list_of_names
BCG1 <- BCG %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
BCG1 <- BCG1[, col_order]

BCGData = BCG1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
HEP <- read.csv(file = 'HEP.csv')
list_of_names = names(HEP)
list_of_names[1]= "country"
for (i in 2:32){
  list_of_names[i] <- 2021 - i
}
names(HEP) <- list_of_names
HEP1 <- HEP %>% slice(-1)

col_order <- c("country", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
HEP1 <- HEP1[, col_order]

HEPData = HEP1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
PCV <- read.csv(file = 'PCV.csv')
list_of_names = names(PCV)
list_of_names[1]= "country"
for (i in 2:13){
  list_of_names[i] <- 2021 - i
}
names(PCV) <- list_of_names
PCV1 <- PCV %>% slice(-1)

col_order <- c("country", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
PCV1 <- PCV1[, col_order]

PCVData = PCV1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
HIB <- read.csv(file = 'HIB.csv')
list_of_names = names(HIB)
list_of_names[1]= "country"
for (i in 2:30){
  list_of_names[i] <- 2021 - i
}
names(HIB) <- list_of_names
HIB1 <- HIB %>% slice(-1)

col_order <- c("country", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
HIB1 <- HIB1[, col_order]

HIBData = HIB1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
PAB <- read.csv(file = 'PAB.csv')
list_of_names = names(PAB)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(PAB) <- list_of_names
PAB1 <- PAB %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
PAB1 <- PAB1[, col_order]

PABData = PAB1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
MCV <- read.csv(file = 'MCV.csv')
list_of_names = names(MCV)
list_of_names[1]= "country"
for (i in 2:21){
  list_of_names[i] <- 2021 - i
}
names(MCV) <- list_of_names
MCV1 <- MCV %>% slice(-1)

col_order <- c("country", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
MCV1 <- MCV1[, col_order]

MCVData = MCV1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r save, echo=FALSE}

MMRCFR_JH <- left_join(CFR_JH, MMRData, by=c('Country'='country'))
MMRCFR_AVG_JH <- ddply(MMRCFR_JH, .(Country, CFR), summarize,  MMR_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

MMRDR_JH <- left_join(DR_JH, MMRData, by=c('Country'='country'))
MMRDR_AVG_JH <- ddply(MMRDR_JH, .(Country, DR), summarize,  MMR_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

dtapCFR_JH <- left_join(CFR_JH, dtapData, by=c('Country'='country'))
dtapCFR_AVG_JH <- ddply(dtapCFR_JH, .(Country, CFR), summarize,  dtap_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

dtapDR_JH <- left_join(DR_JH, dtapData, by=c('Country'='country'))
dtapDR_AVG_JH <- ddply(dtapDR_JH, .(Country, DR), summarize,  dtap_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

ROTCFR_JH <- left_join(CFR_JH, ROTData, by=c('Country'='country'))
ROTCFR_AVG_JH <- ddply(ROTCFR_JH, .(Country, CFR), summarize,  ROT_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

ROTDR_JH <- left_join(DR_JH, ROTData, by=c('Country'='country'))
ROTDR_AVG_JH <- ddply(ROTDR_JH, .(Country, DR), summarize,  ROT_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

POLCFR_JH <- left_join(CFR_JH, POLData, by=c('Country'='country'))
POLCFR_AVG_JH <- ddply(POLCFR_JH, .(Country, CFR), summarize,  POL_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

POLDR_JH <- left_join(DR_JH, POLData, by=c('Country'='country'))
POLDR_AVG_JH <- ddply(POLDR_JH, .(Country, DR), summarize,  POL_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

BCGCFR_JH <- left_join(CFR_JH, BCGData, by=c('Country'='country'))
BCGCFR_AVG_JH <- ddply(BCGCFR_JH, .(Country, CFR), summarize,  BCG_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

BCGDR_JH <- left_join(DR_JH, BCGData, by=c('Country'='country'))
BCGDR_AVG_JH <- ddply(BCGDR_JH, .(Country, DR), summarize,  BCG_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HEPCFR_JH <- left_join(CFR_JH, HEPData, by=c('Country'='country'))
HEPCFR_AVG_JH <- ddply(HEPCFR_JH, .(Country, CFR), summarize,  HEP_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HEPDR_JH <- left_join(DR_JH, HEPData, by=c('Country'='country'))
HEPDR_AVG_JH <- ddply(HEPDR_JH, .(Country, DR), summarize,  HEP_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PCVCFR_JH <- left_join(CFR_JH, PCVData, by=c('Country'='country'))
PCVCFR_AVG_JH <- ddply(PCVCFR_JH, .(Country, CFR), summarize,  PCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PCVDR_JH <- left_join(DR_JH, PCVData, by=c('Country'='country'))
PCVDR_AVG_JH <- ddply(PCVDR_JH, .(Country, DR), summarize,  PCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HIBCFR_JH <- left_join(CFR_JH, HIBData, by=c('Country'='country'))
HIBCFR_AVG_JH <- ddply(HIBCFR_JH, .(Country, CFR), summarize,  HIB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HIBDR_JH <- left_join(DR_JH, HIBData, by=c('Country'='country'))
HIBDR_AVG_JH <- ddply(HIBDR_JH, .(Country, DR), summarize,  HIB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PABCFR_JH <- left_join(CFR_JH, PABData, by=c('Country'='country'))
PABCFR_AVG_JH <- ddply(PABCFR_JH, .(Country, CFR), summarize,  PAB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PABDR_JH <- left_join(DR_JH, PABData, by=c('Country'='country'))
PABDR_AVG_JH <- ddply(PABDR_JH, .(Country, DR), summarize,  PAB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

MCVCFR_JH <- left_join(CFR_JH, MCVData, by=c('Country'='country'))
MCVCFR_AVG_JH <- ddply(MCVCFR_JH, .(Country, CFR), summarize,  MCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

MCVDR_JH <- left_join(DR_JH, MCVData, by=c('Country'='country'))
MCVDR_AVG_JH <- ddply(MCVDR_JH, .(Country, DR), summarize,  MCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

```

```{r save, echo=FALSE}

regMMRCFR_JH <- lm(CFR~MMR_AVG_Coverage, data=MMRCFR_AVG_JH)

with(MMRCFR_AVG_JH, plot(MMR_AVG_Coverage, CFR, main = "MMR Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for MMR Vaccination", ylab = "CFR Level"))
abline(regMMR_JH)

```
```{r save, echo=FALSE}

regMMRDR_JH <- lm(DR~MMR_AVG_Coverage, data=MMRDR_AVG_JH)

with(MMRDR_AVG_JH, plot(MMR_AVG_Coverage, DR, main = "MMR Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for MMR Vaccination", ylab = "DR Level"))
abline(regMMRDR_JH)

```

```{r save, echo=FALSE}

regdtapCFR_JH <- lm(CFR~dtap_AVG_Coverage, data=dtapCFR_AVG_JH)

with(dtapCFR_AVG_JH, plot(dtap_AVG_Coverage, CFR, main = "DTaP Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for DTaP Vaccination", ylab = "CFR Level"))
abline(regdtapCFR_JH)

```
```{r save, echo=FALSE}

regdtapDR_JH <- lm(DR~dtap_AVG_Coverage, data=dtapDR_AVG_JH)

with(dtapDR_AVG_JH, plot(dtap_AVG_Coverage, DR, main = "DTaP Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for DTaP Vaccination", ylab = "DR Level"))
abline(regdtapDR_JH)

```

```{r save, echo=FALSE}

regROTCFR_JH <- lm(CFR~ROT_AVG_Coverage,data=ROTCFR_AVG_JH)

with(ROTCFR_AVG_JH, plot(ROT_AVG_Coverage, CFR, main = "Rotavirus Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Rotavirus Vaccination", ylab = "CFR Level"))
abline(regROTCFR_JH)

```
```{r save, echo=FALSE}

regROTDR_JH <- lm(DR~ROT_AVG_Coverage,data=ROTDR_AVG_JH)

with(ROTDR_AVG_JH, plot(ROT_AVG_Coverage, DR, main = "Rotavirus Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Rotavirus Vaccination", ylab = "DR Level"))
abline(regROTDR_JH)

```

```{r save, echo=FALSE}

regPOLCFR_JH <- lm(CFR~POL_AVG_Coverage,data=POLCFR_AVG_JH)

with(POLCFR_AVG_JH, plot(POL_AVG_Coverage, CFR, main = "Polio Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Polio Vaccination", ylab = "CFR Level"))
abline(regPOLCFR_JH)

```

```{r save, echo=FALSE}

regPOLDR_JH <- lm(DR~POL_AVG_Coverage,data=POLDR_AVG_JH)

with(POLDR_AVG_JH, plot(POL_AVG_Coverage, DR, main = "Polio Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Polio Vaccination", ylab = "DR Level"))
abline(regPOLDR_JH)

```

```{r save, echo=FALSE}

regBCGCFR_JH <- lm(CFR~BCG_AVG_Coverage,data=BCGCFR_AVG_JH)

with(BCGCFR_AVG_JH, plot(BCG_AVG_Coverage, CFR, main = "Tuberculosis Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Tuberculosis Vaccination", ylab = "CFR Level"))
abline(regBCGCFR_JH)

```

```{r save, echo=FALSE}

regBCGDR_JH <- lm(DR~BCG_AVG_Coverage,data=BCGDR_AVG_JH)

with(BCGDR_AVG_JH, plot(BCG_AVG_Coverage, DR, main = "Tuberculosis Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Tuberculosis Vaccination", ylab = "DR Level"))
abline(regBCGDR_JH)

```

```{r save, echo=FALSE}

regHEPCFR_JH <- lm(CFR~HEP_AVG_Coverage,data=HEPCFR_AVG_JH)

with(HEPCFR_AVG_JH, plot(HEP_AVG_Coverage, CFR, main = "Hepatitis B Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Hepatitis B Vaccination", ylab = "CFR Level"))
abline(regHEPCFR_JH)

```

```{r save, echo=FALSE}

regHEPDR_JH <- lm(DR~HEP_AVG_Coverage,data=HEPDR_AVG_JH)

with(HEPDR_AVG_JH, plot(HEP_AVG_Coverage, DR, main = "Hepatitis B Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Hepatitis B Vaccination", ylab = "DR Level"))
abline(regHEPDR_JH)

```

```{r save, echo=FALSE}

regPCVCFR_JH <- lm(CFR~PCV_AVG_Coverage,data=PCVCFR_AVG_JH)

with(PCVCFR_AVG_JH, plot(PCV_AVG_Coverage, CFR, main = "Pneumococcal Conjugate Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Pneumococcal Conjugate Vaccination", ylab = "CFR Level"))
abline(regPCVCFR_JH)

```

```{r save, echo=FALSE}

regPCVDR_JH <- lm(DR~PCV_AVG_Coverage,data=PCVDR_AVG_JH)

with(PCVDR_AVG_JH, plot(PCV_AVG_Coverage, DR, main = "Pneumococcal Conjugate Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Pneumococcal Conjugate Vaccination", ylab = "DR Level"))
abline(regPCVDR_JH)

```

```{r save, echo=FALSE}

regHIBCFR_JH <- lm(CFR~HIB_AVG_Coverage,data=HIBCFR_AVG_JH)

with(HIBCFR_AVG_JH, plot(HIB_AVG_Coverage, CFR, main = "Haemophilus Influenzae Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Haemophilus Influenzae Vaccination", ylab = "CFR Level"))
abline(regHIBCFR_JH)

```

```{r save, echo=FALSE}

regHIBDR_JH <- lm(DR~HIB_AVG_Coverage,data=HIBDR_AVG_JH)

with(HIBDR_AVG_JH, plot(HIB_AVG_Coverage, DR, main = "Haemophilus Influenzae Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Haemophilus Influenzae Vaccination", ylab = "DR Level"))
abline(regHIBDR_JH)

```

```{r save, echo=FALSE}

regPABCFR_JH <- lm(CFR~PAB_AVG_Coverage,data=PABCFR_AVG_JH)

with(PABCFR_AVG_JH, plot(PAB_AVG_Coverage, CFR, main = "Tetanus Prevention at Birth Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Tetanus Prevention at Birth Vaccination", ylab = "CFR Level"))
abline(regPABCFR_JH)

```

```{r save, echo=FALSE}

regPABDR_JH <- lm(DR~PAB_AVG_Coverage,data=PABDR_AVG_JH)

with(PABDR_AVG_JH, plot(PAB_AVG_Coverage, DR, main = "Tetanus Prevention at Birth Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Tetanus Prevention at Birth Vaccination", ylab = "DR Level"))
abline(regPABDR_JH)

```

```{r save, echo=FALSE}

regMCVCFR_JH <- lm(CFR~MCV_AVG_Coverage,data=MCVCFR_AVG_JH)

with(MCVCFR_AVG_JH, plot(MCV_AVG_Coverage, CFR, main = "Measles Dose 2 Vaccine Coverage and Johns Hopkins CFR", xlab = "Average Coverage for Measles Dose 2 Vaccination", ylab = "CFR Level"))
abline(regMCVCFR_JH)

```

```{r save, echo=FALSE}

regMCVDR_JH <- lm(DR~MCV_AVG_Coverage,data=MCVDR_AVG_JH)

with(MCVDR_AVG_JH, plot(MCV_AVG_Coverage, DR, main = "Measles Dose 2 Vaccine Coverage and Johns Hopkins DR", xlab = "Average Coverage for Measles Dose 2 Vaccination", ylab = "DR Level"))
abline(regMCVDR_JH)

```

```{r save, echo=FALSE}

summary(regMMRCFR_JH)$r.squared 
summary(regdtapCFR_JH)$r.squared 
summary(regROTCFR_JH)$r.squared 
summary(regPOLCFR_JH)$r.squared 
summary(regBCGCFR_JH)$r.squared 
summary(regHEPCFR_JH)$r.squared 
summary(regPCVCFR_JH)$r.squared
summary(regHIBCFR_JH)$r.squared
summary(regPABCFR_JH)$r.squared 
summary(regMCVCFR_JH)$r.squared 

```

```{r save, echo=FALSE}

ALLCFR_AVG_JH <- list(MMRCFR_AVG_JH, dtapCFR_AVG_JH, ROTCFR_AVG_JH, POLCFR_AVG_JH, BCGCFR_AVG_JH, HEPCFR_AVG_JH, PCVCFR_AVG_JH, HIBCFR_AVG_JH, PABCFR_AVG_JH, MCVCFR_AVG_JH ) %>% reduce(left_join, by="Country") %>% select ('Country', 'CFR.x', 'MMR_AVG_Coverage', 'dtap_AVG_Coverage', 'ROT_AVG_Coverage', 'POL_AVG_Coverage', 'BCG_AVG_Coverage', 'HEP_AVG_Coverage', 'PCV_AVG_Coverage', 'HIB_AVG_Coverage', 'PAB_AVG_Coverage', 'MCV_AVG_Coverage') %>% drop_na()

```

```{r save, echo=FALSE}

fitCFR <- lm(CFR.x ~ MMR_AVG_Coverage + dtap_AVG_Coverage + ROT_AVG_Coverage + POL_AVG_Coverage + BCG_AVG_Coverage + HEP_AVG_Coverage + PCV_AVG_Coverage + HIB_AVG_Coverage + PAB_AVG_Coverage +MCV_AVG_Coverage, data=ALLCFR_AVG_JH)
summary(fitCFR)
plot(fitCFR)

```


```{r save, echo=FALSE}

fitCFR_subset <- lm(CFR.x ~ dtap_AVG_Coverage  + POL_AVG_Coverage, data=ALLCFR_AVG_JH)
summary(fitCFR_subset)
plot(fitCFR_subset)

```


```{r save, echo=FALSE}
MMR12CFR <- left_join(MMRCFR_AVG, MCVCFR_AVG, by=c('Country'='Country')) %>% select('Country', 'CFR.x', 'MMR_AVG_Coverage', 'MCV_AVG_Coverage')%>% drop_na()

colnames(MMR12CFR) <- c('Country', 'CFR', 'Dose1_AVG_Coverage', 'Dose2_AVG_Coverage')

fit <- lm(CFR ~ Dose1_AVG_Coverage + Dose2_AVG_Coverage, data=MMR12CFR)
summary(fit)
plot(fit)

```

```{r save, echo=FALSE}
regMMR12 <- lm(CFR~Dose1_AVG_Coverage, Dose2_AVG_Coverage,data=MMR12CFR)

with(MCVCFR_AVG, plot(MCV_AVG_Coverage, CFR, main = "Measles Dose 2 Vaccine Coverage and CFR", xlab = "Average Coverage for Measles Dose 2 Vaccination", ylab = "CFR Level"))
abline(regMMR12)

summary(regMMR12)$r.squared 
```

