---
title: "DATA606Graphs"
author: "Selma Gomez Orr"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages,  eval=TRUE, include=FALSE}
library(tidyverse)
library(knitr)
library(purrr)
```


```{r plot, echo=FALSE, eval=TRUE}
# Simple Horizontal Bar Plot with Added Labels
counts <- list(20, 15, 31, 353, 1457, 3809, 10057, 23991, 40613, 49871, 58253)

barplot(unlist(counts), main="Age Distribution of COVID-19 Deaths", horiz=TRUE, col=terrain.colors(11), legend=TRUE, 
)
```
```{r newplot, echo=FALSE, eval=TRUE}
# Simple Horizontal Bar Plot with Added Labels
df <- data.frame(count=c(20, 15, 31, 353, 1457, 3809, 10057, 23991, 40613, 49871, 58253),
                ages=c("<1", "01-04", "05-14", "15-24", "25-34", "35-44", "45-54", "55-64", "65-74","75-84", "85 or more"))

pdf('cdcData.pdf', width=5, height=5) 

plt <- ggplot(data=df, 
              aes(x=count, y=ages, fill=count)) +
  geom_bar(stat="identity")

plt + 
  labs(x = 'Number of Deaths',
       y = 'Age (years)',
       fill = 'Count',
       title = "Age Distribution of COVID-19 Deaths",
       subtitle = "U.S. Figures Based on CDC Data through September 2020"
)
dev.off()

```

