---
title: "DRAge16Countries"
author: "Selma Gomez Orr"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages,  eval=TRUE, include=FALSE}
library(tidyverse)
library(purrr)
library(plyr)
```

```{r clean, echo=FALSE}
data_DR_Age <- read.csv(file = 'DRAge16C.csv')
names(data_DR_Age) = c("Country", "DR1","DR2", "DR3")
DR_Age<- data_DR_Age %>% select("Country", "DR1")
```

```{r clean, echo=FALSE}
MMR <- read.csv(file = 'MMR1.csv')
list_of_names = names(MMR)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(MMR) <- list_of_names
MMR1 <- MMR %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
MMR1 <- MMR1[, col_order]

MMRData = MMR1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
dtap <- read.csv(file = 'dtap.csv')
list_of_names = names(dtap)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(dtap) <- list_of_names
dtap1 <- dtap %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
dtap1 <- dtap1[, col_order]

dtapData = dtap1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
ROT <- read.csv(file = 'ROT.csv')
list_of_names = names(ROT)
list_of_names[1]= "country"
for (i in 2:15){
  list_of_names[i] <- 2021 - i
}
names(ROT) <- list_of_names
ROT1 <- ROT %>% slice(-1)

col_order <- c("country", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
ROT1 <- ROT1[, col_order]

ROTData = ROT1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
POL <- read.csv(file = 'POL.csv')
list_of_names = names(POL)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(POL) <- list_of_names
POL1 <- POL %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
POL1 <- POL1[, col_order]

POLData = POL1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
BCG <- read.csv(file = 'BCG.csv')
list_of_names = names(BCG)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(BCG) <- list_of_names
BCG1 <- BCG %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
BCG1 <- BCG1[, col_order]

BCGData = BCG1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
HEP <- read.csv(file = 'HEP.csv')
list_of_names = names(HEP)
list_of_names[1]= "country"
for (i in 2:32){
  list_of_names[i] <- 2021 - i
}
names(HEP) <- list_of_names
HEP1 <- HEP %>% slice(-1)

col_order <- c("country", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
HEP1 <- HEP1[, col_order]

HEPData = HEP1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
PCV <- read.csv(file = 'PCV.csv')
list_of_names = names(PCV)
list_of_names[1]= "country"
for (i in 2:13){
  list_of_names[i] <- 2021 - i
}
names(PCV) <- list_of_names
PCV1 <- PCV %>% slice(-1)

col_order <- c("country", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
PCV1 <- PCV1[, col_order]

PCVData = PCV1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
HIB <- read.csv(file = 'HIB.csv')
list_of_names = names(HIB)
list_of_names[1]= "country"
for (i in 2:30){
  list_of_names[i] <- 2021 - i
}
names(HIB) <- list_of_names
HIB1 <- HIB %>% slice(-1)

col_order <- c("country", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
HIB1 <- HIB1[, col_order]

HIBData = HIB1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
PAB <- read.csv(file = 'PAB.csv')
list_of_names = names(PAB)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(PAB) <- list_of_names
PAB1 <- PAB %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
PAB1 <- PAB1[, col_order]

PABData = PAB1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r clean, echo=FALSE}
MCV <- read.csv(file = 'MCV.csv')
list_of_names = names(MCV)
list_of_names[1]= "country"
for (i in 2:21){
  list_of_names[i] <- 2021 - i
}
names(MCV) <- list_of_names
MCV1 <- MCV %>% slice(-1)

col_order <- c("country", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
MCV1 <- MCV1[, col_order]

MCVData = MCV1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r save, echo=FALSE}

MMRDR <- left_join(DR_Age, MMRData, by=c('Country'='country'))
MMRDR_AVG <- ddply(MMRDR, .(Country, DR1), summarize,  MMR_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

dtapDR <- left_join(DR_Age, dtapData, by=c('Country'='country'))
dtapDR_AVG <- ddply(dtapDR, .(Country, DR1), summarize,  dtap_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

ROTDR <- left_join(DR_Age, ROTData, by=c('Country'='country'))
ROTDR_AVG <- ddply(ROTDR, .(Country, DR1), summarize,  ROT_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na() 

POLDR <- left_join(DR_Age, POLData, by=c('Country'='country'))
POLDR_AVG <- ddply(POLDR, .(Country, DR1), summarize,  POL_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

BCGDR <- left_join(DR_Age, BCGData, by=c('Country'='country'))
BCGDR_AVG <- ddply(BCGDR, .(Country, DR1), summarize,  BCG_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HEPDR <- left_join(DR_Age, HEPData, by=c('Country'='country'))
HEPDR_AVG <- ddply(HEPDR, .(Country, DR1), summarize,  HEP_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PCVDR <- left_join(DR_Age, PCVData, by=c('Country'='country'))
PCVDR_AVG <- ddply(PCVDR, .(Country, DR1), summarize,  PCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

HIBDR <- left_join(DR_Age, HIBData, by=c('Country'='country'))
HIBDR_AVG <- ddply(HIBDR, .(Country, DR1), summarize,  HIB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

PABDR <- left_join(DR_Age, PABData, by=c('Country'='country'))
PABDR_AVG <- ddply(PABDR, .(Country, DR1), summarize,  PAB_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

MCVDR <- left_join(DR_Age, MCVData, by=c('Country'='country'))
MCVDR_AVG <- ddply(MCVDR, .(Country, DR1), summarize,  MCV_AVG_Coverage=mean(coverage, na.rm=TRUE)) %>% drop_na()

```

```{r save, echo=FALSE}

regMMRDR <- lm(DR1~MMR_AVG_Coverage, data=MMRDR_AVG)

with(MMRDR_AVG, plot(MMR_AVG_Coverage, DR1, main = "MMR Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for MMR Vaccination", ylab = "DR Level"))
abline(regMMRDR)

```

```{r save, echo=FALSE}

regdtapDR <- lm(DR1~dtap_AVG_Coverage, data=dtapDR_AVG)

with(dtapDR_AVG, plot(dtap_AVG_Coverage, DR1, main = "DTaP Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for DTaP Vaccination", ylab = "DR Level"))
abline(regdtapDR)

```

```{r save, echo=FALSE}

regROTDR <- lm(DR1~ROT_AVG_Coverage,data=ROTDR_AVG)

with(ROTDR_AVG, plot(ROT_AVG_Coverage, DR1, main = "Rotavirus Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for Rotavirus Vaccination", ylab = "DR Level"))
abline(regROTDR)

```

```{r save, echo=FALSE}

regPOLDR <- lm(DR1~POL_AVG_Coverage,data=POLDR_AVG)

with(POLDR_AVG, plot(POL_AVG_Coverage, DR1, main = "Polio Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for Polio Vaccination", ylab = "DR Level"))
abline(regPOLDR)

```

```{r save, echo=FALSE}

regBCGDR <- lm(DR1~BCG_AVG_Coverage,data=BCGDR_AVG)

with(BCGDR_AVG, plot(BCG_AVG_Coverage, DR1, main = "Tuberculosis Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for Tuberculosis Vaccination", ylab = "DR Level"))
abline(regBCGDR)

```

```{r save, echo=FALSE}

regHEPDR <- lm(DR1~HEP_AVG_Coverage,data=HEPDR_AVG)

with(HEPDR_AVG, plot(HEP_AVG_Coverage, DR1, main = "Hepatitis B Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for Hepatitis B Vaccination", ylab = "CFR Level"))
abline(regHEPDR)

```

```{r save, echo=FALSE}

regPCVDR <- lm(DR1~PCV_AVG_Coverage,data=PCVDR_AVG)

with(PCVDR_AVG, plot(PCV_AVG_Coverage, DR1, main = "Pneumococcal Conjugate Vaccine Coverage and DR Ages 0 to 54", xlab = "Average Coverage for Pneumococcal Conjugate Vaccination", ylab = "DR Level"))
abline(regPCVDR)

```

```{r save, echo=FALSE}

regHIBDR <- lm(DR1~HIB_AVG_Coverage,data=HIBDR_AVG)

with(HIBDR_AVG, plot(HIB_AVG_Coverage, DR1, main = "Haemophilus Influenzae Vaccine Coverage and DR Ages 0 to 54", xlab = "Average Coverage for Haemophilus Influenzae Vaccination", ylab = "DR Level"))
abline(regHIBDR)

```

```{r save, echo=FALSE}

regPABDR <- lm(DR1~PAB_AVG_Coverage,data=PABDR_AVG)

with(PABDR_AVG, plot(PAB_AVG_Coverage, DR1, main = "Tetanus Prevention at Birth Vaccine Coverage and DR for Ages 0 to 54", xlab = "Average Coverage for Tetanus Prevention at Birth Vaccination", ylab = "DR Level"))

```

```{r save, echo=FALSE}

regMCVDR <- lm(DR1~MCV_AVG_Coverage,data=MCVDR_AVG)

with(MCVDR_AVG, plot(MCV_AVG_Coverage, DR1, main = "Measles Dose 2 Vaccine Coverage DR for Ages 0 to 54", xlab = "Average Coverage for Measles Dose 2 Vaccination", ylab = "DR Level"))
abline(regMCVDR)

```

```{r save, echo=FALSE}

summary(regMMRDR)$r.squared 
summary(regdtapDR)$r.squared 
summary(regROTDR)$r.squared 
summary(regPOLDR)$r.squared 
summary(regBCGDR)$r.squared 
summary(regHEPDR)$r.squared 
summary(regPCVDR)$r.squared
summary(regHIBDR)$r.squared
summary(regPABDR)$r.squared 
summary(regMCVDR)$r.squared 

```
