---
title: "DTaP Data Summary"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages,  eval=TRUE, include=FALSE}
library(tidyverse)
library(purrr)
```

```{r clean, echo=FALSE}
DTAPclean <- read.csv(file = 'dtap.csv')
list_of_names = names(DTAPclean)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(DTAPclean) <- list_of_names
DTAP1clean <- DTAPclean %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
DTAP1clean <- DTAP1clean[, col_order]

DTAP1clean <- DTAP1clean[, col_order]

#Create columns that are the means for different age groups.
DTAP1clean$years_0to9 <- rowMeans(DTAP1clean[,c('2019', '2018','2017', '2016', '2015', '2014', '2013', '2012', '2011')], na.rm=TRUE)
 
DTAP1clean$years_10to19 <- rowMeans(DTAP1clean[,c('2010', '2009', '2008','2007', '2006', '2005', '2004', '2003', '2002', '2001')], na.rm=TRUE) 

DTAP1clean$years_20to29 <- rowMeans(DTAP1clean[,c('2000','1999', '1998','1997', '1996', '1995', '1994', '1993', '1992', '1991')], na.rm=TRUE)

DTAP1clean$years_30to39 <- rowMeans(DTAP1clean[,c('1990','1989', '1988','1987', '1986', '1985', '1984', '1983', '1982', '1981')], na.rm=TRUE)
 
DTAP1clean$years_40 <- rowMeans(DTAP1clean[,c('1980', '1980')], na.rm=TRUE)

```



```{r summary, eval=TRUE, echo=FALSE, warning=FALSE, include = TRUE, results = 'asis'}

#Create a dataframe of just the columns of interest and round values.
DTAP_age <- DTAP1clean %>% select(country, starts_with("years"))
temp <-names(DTAP_age)[2:6]

DTAP_age[,temp]=round(DTAP_age[,temp],1)

our_summary1 <-
  list("Ages 0 to 9 years" =
       list("min"       = ~ min(.data$years_0to9, na.rm=TRUE),
            "median"    = ~ median(.data$years_0to9, na.rm=TRUE),
            "max"       = ~ max(.data$years_0to9, na.rm=TRUE),
            "sd"        = ~ sd(.data$years_0to9, na.rm=TRUE),
            "mean"      = ~ mean(.data$years_0to9, na.rm=TRUE)),
       "Ages 10 to 19 years" =
       list("min"       = ~ min(.data$years_10to19, na.rm=TRUE),
            "median"    = ~ median(.data$years_10to19, na.rm=TRUE),
            "max"       = ~ max(.data$years_10to19, na.rm=TRUE),
            "sd"        = ~ sd(.data$years_10to19, na.rm=TRUE),
            "mean"      = ~ mean(.data$years_10to19, na.rm=TRUE)),
       "Ages 20 to 29 years" =
       list("min"       = ~ min(.data$years_20to29, na.rm=TRUE),
            "median"    = ~ median(.data$years_20to29, na.rm=TRUE),
            "max"       = ~ max(.data$years_20to29, na.rm=TRUE),
            "sd"        = ~ sd(.data$years_20to29, na.rm=TRUE),
            "mean"      = ~ mean(.data$years_20to29, na.rm=TRUE)),
       "Ages 30 to 39 years" =
      list("min"       = ~ min(.data$years_30to39, na.rm=TRUE),
            "median"    = ~ median(.data$years_30to39, na.rm=TRUE),
            "max"       = ~ max(.data$years_30to39, na.rm=TRUE),
            "sd"        = ~ sd(.data$years_30to39, na.rm=TRUE),
            "mean"      = ~ mean(.data$years_30to39, na.rm=TRUE)),
      "Age 40 years" =
      list("min"       = ~ min(.data$years_40, na.rm=TRUE),
            "median"    = ~ median(.data$years_40, na.rm=TRUE),
            "max"       = ~ max(.data$years_40, na.rm=TRUE),
            "sd"        = ~ sd(.data$years_40, na.rm=TRUE),
            "mean"      = ~ mean(.data$years_40, na.rm=TRUE))
       )


library(qwraps2)


options(qwraps2_markup = 'markdown')

DTAP_summary <- summary_table(DTAP_age, our_summary1)

DTAP_summary

```



```{r graph, eval=TRUE, echo=FALSE}

DTAP_graph <- DTAP_age %>%
  select("country", "years_0to9", "years_10to19", "years_20to29", "years_30to39") %>%
  na.omit()

DTAP_new_graph <- DTAP_graph %>%
  pivot_longer(!country, names_to = "Age", values_to = "Coverage_DTaP")

test <- DTAP_new_graph%>%
  filter(country=="Brazil"| country=="Spain" | country=="United States of America" | country=="Japan" | country=="Kenya" | country=="Egypt")
  

library(ggplot2)
# Basic scatter plot

ggplot(test, aes(x=Age, y=Coverage_DTaP, color=country)) + geom_point()

```


```{r graph2, eval=TRUE, echo=FALSE}

ggplot(DTAP_new_graph, aes(x=Age, y=Coverage_DTaP)) + geom_point()

```