---
title: "DataMungingDtap"
author: "Selma Gomez Orr"
date: "10/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages,  eval=TRUE, include=FALSE}
library(tidyverse)
library(purrr)
```

```{r clean, echo=FALSE}
dtap <- read.csv(file = 'dtap.csv')
list_of_names = names(dtap)
list_of_names[1]= "country"
for (i in 2:41){
  list_of_names[i] <- 2021 - i
}
names(dtap) <- list_of_names
dtap1 <- dtap %>% slice(-1)

col_order <- c("country", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
dtap1 <- dtap1[, col_order]

dtap2 = dtap1 %>%
  pivot_longer(!country, names_to = "year", values_to = "coverage")
```

```{r save, echo=FALSE}
isoCodes <- read.csv(file = 'CountryIso.csv')
isoCodes <- isoCodes %>%
  select(country, iso_alpha)

dtapChloro <- left_join(dtap2, isoCodes, by=c('country'='country'))

```

```{r save, echo=FALSE}

write.csv(dtapChloro,'dtapMap.csv')
```